import {
	Car,
	Droplet,
	Dumbbell,
	Flame,
	Gamepad2,
	Gift,
	GraduationCap,
	HeartPulse,
	Home,
	Landmark,
	Laptop,
	type LucideIcon,
	MoreHorizontal,
	PawPrint,
	Phone,
	Plane,
	PlusCircle,
	Repeat,
	Shirt,
	ShoppingBag,
	ShoppingCart,
	Utensils,
	Wallet,
	Wifi,
	Zap,
} from "lucide-react";

export const ICON_OPTIONS: Array<{ name: string; icon: LucideIcon }> = [
	{ name: "ShoppingCart", icon: ShoppingCart },
	{ name: "Car", icon: Car },
	{ name: "Home", icon: Home },
	{ name: "Landmark", icon: Landmark },
	{ name: "Zap", icon: Zap },
	{ name: "Droplet", icon: Droplet },
	{ name: "Flame", icon: Flame },
	{ name: "Wifi", icon: Wifi },
	{ name: "Phone", icon: Phone },
	{ name: "Gamepad2", icon: Gamepad2 },
	{ name: "HeartPulse", icon: HeartPulse },
	{ name: "ShoppingBag", icon: ShoppingBag },
	{ name: "Repeat", icon: Repeat },
	{ name: "Wallet", icon: Wallet },
	{ name: "Laptop", icon: Laptop },
	{ name: "GraduationCap", icon: GraduationCap },
	{ name: "Plane", icon: Plane },
	{ name: "Utensils", icon: Utensils },
	{ name: "Dumbbell", icon: Dumbbell },
	{ name: "PawPrint", icon: PawPrint },
	{ name: "Gift", icon: Gift },
	{ name: "Shirt", icon: Shirt },
	{ name: "PlusCircle", icon: PlusCircle },
	{ name: "MoreHorizontal", icon: MoreHorizontal },
];

export const ICONS: Record<string, LucideIcon> = Object.fromEntries(
	ICON_OPTIONS.map(({ name, icon }) => [name, icon]),
);
